data:
  ds_path: "/home/christian/vae/data_nb_1/b"
  batch_size: 64
  val_split: 0.1
  test_split: 0.0
  num_workers: 4
  seed: 42
  pin_memory: true

model:
  learning_rate: 0.0001
  beta_warmup_steps: 10000
  lr_schedule: "cosine"

trainer:
  max_epochs: 5
  devices: 1
  accelerator: "auto"
  log_every_n_steps: 50
  deterministic: false
  precision: "bf16-mixed"
  gradient_clip_val: 1.0
