inherit: default_512
name: "26_beta_0.2_512d_free_bits_24_new_data_beta_exp"

data:
  ds_path: "/home/christian/vae/data_nb_1_combined"

model:
  beta_end: 0.2
  free_bits: 24
  beta_warmup_steps: 0
  beta_decay_rate: 0.99999

trainer:
  max_epochs: 1
