inherit: default_512
name: "27_A40_beta_0.2_512d_free_bits_24_new_data_beta_exp_ss_2000"

data:
  ds_path: "/root/christian/data_nb_1_combined"

model:
  beta_end: 0.2
  free_bits: 24
  beta_warmup_steps: 0
  beta_decay_rate: 0.99999
  scheduled_sampling: true
  scheduled_sampling_rate: 2000

trainer:
  max_epochs: 1
  devices: 8
